### ISSUE TITLE
Error when connect to admin panel

### ISSUE THREAD

**Issue by Dilemmast** [mahdigholipour3/bottelegrammarzban#10]
hi , i'm getting an error when connect bot to the vps .
in telegram bot when i create a new panel all of details is correct but can't connect to vps.
my error logs in host show this error :
Trying to access array offset on value of type null in /home/index.php on line 1572
i'm setting up detail like this : 
panel name : Test
panel url : for example like this -> http://11.11.11.11 (using with port 443 and not type in url)
username : admin
password : admin
ufw is already disabled and all of ports are open
working with Marzaban x-ui
panel going up when type my url like this -> http://11.11.11.11:443/dashboard/ in web apps
thank's regards.

**Comment by mahdigholipour3** [comment]
Hello.
  Send robot token and if you can contact me via telegram

My telegram ID
@mahdigh9
________________________________
From: Dilemmast ***@***.***>
Sent: Thursday, June 22, 2023 1:53:10 AM
To: mahdigholipour3/bottelegrammarzban ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mahdigholipour3/bottelegrammarzban] Error when connect to admin panel (Issue #10)


hi , i'm getting an error when connect bot to the vps .
in telegram bot when i create a new panel all of details is correct but can't connect to vps.
my error logs in host show this error :
Trying to access array offset on value of type null in /home/index.php on line 1572
i'm setting up detail like this :
panel name : Test
panel url : for example like this -> http://11.11.11.11 (using with port 443 and not type in url)
username : admin
password : admin
ufw is already disabled and all of ports are open
working with Marzaban x-ui
panel going up when type my url in web apps.
thank's regards.

**Comment by Dilemmast** [comment]
@mahdigholipour3  your telegram id @mahdigh9 not found!

**Comment by mahdigholipour3** [comment]
Hi my username is not


My telegram username is this
@mahdigh9
________________________________
