### ISSUE TITLE
instant sell in insufficient balance

### ISSUE THREAD

**Issue by cloudffff** [mahdigholipour3/bottelegrammarzban#13]
سلام
اگر این امکان اضافه بشه که به کاربر بعد از سفارش یک سرویس، وقتی موجودیش کافی نیست، به جای اینکه ربات بگه برو تو منو و افزایش موجودی بده و بعد دوباره بیا خرید کن؛ اینطور میبود که ربات درجا هزینه رو میگفت و کاربر فیش رو میفرستاد و همون سرویس رو بهش میداد، کار با ربات برای کاربر راحت تر میشد.
مرسی از زحماتت💕

**Comment by mahdigholipour3** [comment]
Hi applied
[08ad47a](https://github.com/mahdigholipour3/bottelegrammarzban/commit/08ad47aa39e2fa0144d14f037334d98fddb58f30)
