### ISSUE TITLE
مشکل در ارسال دلیل رد شدن پرداخت

### ISSUE THREAD

**Issue by AtashzadArash** [mahdigholipour3/bottelegrammarzban#16]
سلام.
اول یک خسته نباشید به آقا مهدی عزیز برا ساخت این ربات عالی🌷.
بعداز اینکه کسی پرداخت انجام میده (از طریق کارت به کارت) و میخوام درخواست پرداختش رو رد کنم ،دلیل و پیام رد شدن برای کاربر فرستاده نمیشه.
البته اگه با اکانت خودم یعنی ادمین درخواست خودم رو رد کنم دلیلش برام ارسال میشه اما برا کاربرها نمیشه...
ممنون میشم بررسی کنید ❤

**Comment by mahdigholipour3** [comment]
Hello Fixed Bug [5c38de8](https://github.com/mahdigholipour3/bottelegrammarzban/commit/5c38de88cf9232ea6bc5868cec5b19a85af52cbf)
