### ISSUE TITLE
امکان تعریف مشتری اعتباری

### ISSUE THREAD

**Issue by tohid3aeed** [mahdigholipour3/bottelegrammarzban#9]
خسته نباشید
عالی میشه اگه امکان تعریف مشتری اعتباری هم اضافه بشه
تشکر از زحماتتون

**Comment by mahdigholipour3** [comment]
سلام لطفا بیشتر توضیح بدید منظورتون از مشتری اعتباری چیه

**Comment by tohid3aeed** [comment]
سلام من با برخی از همکاران موبایل فروش تسویه ام اینجوریه که هر موقع حجم
اکانت تموم شد تسویه کنم.
اینکه اجازه بدم بعضی از مشتری ها بتونن بدون پرداخت هزینه کانفیگ تهیه کنن
نیازه
